### PR TITLE
Rectifying argument fetch for git organization and branch

### PR DESCRIPTION
**Pull request by vishmegh88**
Refer : https://argparse4j.github.io/usage.html#arguments-store

### CODE REVIEW

**Comment by vishmegh88** [comment]
@afalko @justinharringa Please review. Thanks.

**Comment by afalko** [comment]
I like this change; makes things more explicit and cleaner. 

I'm working on testing this out locally and maybe getting the integration test working again.

**Comment by afalko** [comment]
This passed locally with itest. I'm going to have a fix for the itests later today.

**Comment by afalko** [comment]
I broke this after merging conflicts. Working on fixing that and merging.

**Pull request merged**
